Add RSA SHA2-256 and SHA2-512 support by accepting ext-info packets
connectbot/trilead-ssh2 pull request #36
Opened 2018-01-23 23:31 UTC by slix

Adds SHA2 support for client authentication, ssh-agent authentication,
and server host keys.

Accepts ext-info packets from the server. Only "server-sig-algs" is used
atm.

2018-01-24 01:34 UTC, slix commented
SSH has a new feature that allows RSA keys to use SHA2 signatures instead of SHA1 signatures. Which is important because SHA1 has been partially broken. RSA now supports multiple hashing algorithms despite using the same format for the public key itself, and only some servers support this.

The other implementation option was trying SHA2-512 then SHA2-256 then SHA1. But servers would count that against authentication retries, which might be problematic.

See https://tools.ietf.org/html/draft-ietf-curdle-rsa-sha2-12 and https://tools.ietf.org/html/draft-ietf-curdle-ssh-ext-info-15

2018-01-24 02:00 UTC, kruton commented
Thanks, Peter. It will take me a while to review this patch, but I will
take a look at it.

>

2018-01-24 04:13 UTC, slix commented
Thanks!

~250 of the added lines are copy-pasting most of RSASHA1Verify into RSASHA256Verify and RSASHA512Verify. Maybe the patch would be smaller if I move the common code to a utility class or get git to detect the copies.

2018-04-06 01:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/connectbot/sshlib?pullRequest=36) <br/>All committers have signed the CLA.

2018-04-09 21:17 UTC, slix commented
Do I need to sign the CLA? I did this on work time and with my @google.com email.

2018-04-10 02:00 UTC, kruton commented
Yes, this project is not governed by Google. However, it's licensed under 3-clause BSD which should be easy.

2018-04-10 04:22 UTC, kruton requested changes

2018-04-10 04:22 UTC, kruton commented on sshlib/src/main/java/com/trilead/ssh2/ExtensionInfo.java
> +			return new ExtensionInfo(Collections.emptySet());
Java 7 has a problem with this. Can be fixed with:
```java
Collections.<String>emptySet()
```

2018-04-10 04:22 UTC, kruton commented on sshlib/src/main/java/com/trilead/ssh2/ExtensionInfo.java
> +		return new ExtensionInfo(Collections.emptySet());
Java 7 has a problem with this. Can be fixed with:
```java
Collections.<String>emptySet()
```

2018-04-13 01:22 UTC, slix commented on sshlib/src/main/java/com/trilead/ssh2/ExtensionInfo.java
> +		return new ExtensionInfo(Collections.emptySet());
Fixed

2018-04-13 01:22 UTC, slix commented on sshlib/src/main/java/com/trilead/ssh2/ExtensionInfo.java
> +			return new ExtensionInfo(Collections.emptySet());
Fixed

2018-04-13 22:15 UTC, slix commented
Signed CLA.

2018-04-15 14:03 UTC, kruton approved these changes

2018-04-15 14:04 UTC, kruton commented
Thanks for the contribution @slix and Google.

2018-04-15 14:04 UTC, merged